# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KannaTest02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KannaTest02
pod 'Kanna','~>5.0.0'

  target 'KannaTest02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KannaTest02UITests' do
    # Pods for testing
  end

end
